name: Scanners 

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  npm_audit:
    runs-on: ubuntu-latest
    name: NPM Audit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: npm audit
        run: npm audit --omit dev

  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Scan
        id: scan
        run: |
          set -eo pipefail;
          python3 -m pip install semgrep;
          semgrep scan --error --config .semgrep/