name: Scanners 

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  npm_audit:
    runs-on: ubuntu-latest
    name: NPM Audit
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: pnpm audit
        run: pnpm audit --prod

  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Scan
        id: scan
        run: |
          set -eo pipefail;
          python3 -m pip install semgrep;
          semgrep scan --error --config .semgrep/