name: Test

on: [push, pull_request]

jobs:
  service-token-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: npm run test
        env:
          NODE_ENV: development
          DOPPLER_TOKEN: ${{ secrets.TEST_DOPPLER_TOKEN }}
  service-account-token-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install
      - run: npm run test
        env:
          NODE_ENV: development
          DOPPLER_TOKEN: ${{ secrets.TEST_DOPPLER_SA_TOKEN }}
          DOPPLER_PROJECT: secrets-fetch-action
          DOPPLER_CONFIG: test
